"""empty message

Revision ID: 22f81df3aedd
Revises: 229f2675e9d0
Create Date: 2020-03-11 23:36:43.136149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f81df3aedd'
down_revision = '229f2675e9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('favoritecolor', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'person', ['favoritecolor'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'favoritecolor')
    # ### end Alembic commands ###
